title: Jean Pierre Blog Tecnologia 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jean Pierre F Theodoro # add your name
author-img: profile.jpeg # add your photo
about-author: Profissional Formado em ADS com ampla experiencia em Infraestrutura e Redes, e apaixonado por Tecnologia e Videogame  # add description
social-twitter: HelpdeskJp # add your Twitter handle
#social-facebook: JeanPierreHelpDesk # add your Facebook handle
social-github: jeanpierreft # add your Github handle
social-linkedin: jeanpierrefernandesTheodoro # add your Linkedin handle
social-email: jphelpdesk@outlook.com.br
social-instagram: jp.helpdesk
social-youtube: UCRmrAAfvmYO8rg-ng_451Ig

# Disqus
discus-identifier: jphelpdesk # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
